Repository trueos/trueos, pull requests merged in 2018-06, with the labels that each got.

#71 add ascii logo
  stand/forth/logo-trident.4th
Labels: review

#72 - Update poudriere to 3.2.7
  contrib/poudriere/src/bin/poudriere
  contrib/poudriere/src/share/poudriere/html/assets/poudriere.js
Labels: review

#75 - Disable - Warning: Major OS version upgrade detected.
  contrib/pkg/src/main.c
Labels: review

#74 Fix building poudriere "sh" and leaving leftovers in the tree, oops!
  libexec/poudriere/sh/Makefile
Labels: review

#79 Enable the Lua Loader which fixes #78
  share/mk/src.opts.mk
  stand/defaults/loader.conf
  stand/lua/Makefile
  stand/lua/brand-trueos.lua
  stand/lua/drawer.lua
Labels: review

#84 Add missing kldxref service
  etc/Makefile
  etc/init.d/Makefile
  etc/init.d/kldxref
Labels: review

#86 Boot mute fix
  stand/common/boot.c
  stand/common/bootstrap.h
  stand/common/metadata.c
  stand/defs.mk
  stand/efi/loader/bootinfo.c
  stand/efi/loader/main.c
  stand/i386/gptboot/Makefile
  stand/i386/gptzfsboot/Makefile
  stand/i386/isoboot/Makefile
  stand/i386/libi386/bootinfo.c
  stand/i386/zfsboot/Makefile
  stand/userboot/userboot/bootinfo.c
Labels: cherry-pick, enhancement, review

#85 Add in the Trident brand/logo files for the Lua loader.
  stand/lua/Makefile
  stand/lua/brand-trident.lua
  stand/lua/logo-trident.lua
Labels: review

#87 Enable eager FPU context switch by default on amd64.
  sys/amd64/amd64/cpu_switch.S
  sys/amd64/amd64/fpu.c
Labels: cherry-pick, review

#76 Update Makefile
  sbin/rc-service/Makefile
Labels: review

#90 Adding ability to have auto-install file on an additional disk
  release/rc.local
  usr.sbin/pc-sysinstall/backend/startautoinstall.sh
Labels: review

#93 Pc sysinstall fixes
  release/rc.local
  usr.sbin/pc-sysinstall/backend/functions-bsdlabel.sh
  usr.sbin/pc-sysinstall/backend/functions-newfs.sh
Labels: bug, review

#94 Fix console spam
  sys/amd64/amd64/fpu.c
  sys/i386/i386/npx.c
  sys/i386/i386/swtch.s
Labels: review

#97 Update release-trueos.sh
  release/release-trueos.sh
Labels: bug, review

#98 Update release-trueos.sh
  release/release-trueos.sh
Labels: review

#100 Update release-trueos.sh
  release/release-trueos.sh
Labels: review

#101 - Add bhyve PCIe-NVMe device emulation.
  usr.sbin/bhyve/Makefile
  usr.sbin/bhyve/bhyve.8
  usr.sbin/bhyve/block_if.h
  usr.sbin/bhyve/pci_nvme.c
Labels: review

#102 Update README.md
  release/README.md
Labels: review

#104 switch to editors/vim-console
  release/manifests/trueos-snapshot.json
Labels: review

#103 Add ipmitool and dmidecode to build as essential troubleshooting tools.
  release/manifests/trueos-master.json
  release/manifests/trueos-snapshot.json
  release/manifests/trueos-stable.json
  release/trueos-manifest.json
Labels: enhancement, review
