Repository trueos/trueos, pull requests merged in 2018-10, with the labels that each got.

#174 Import TrueOS tests from old trueos-server project
  tests/boot.exp
  tests/install.exp
  tests/iso/.keepme
Labels: review

#172 Many enhances today:
  Jenkins/Jenkinsfile-Plasma-Unstable
  Jenkins/Jenkinsfile-master
  Jenkins/Jenkinsfile-snapshots
  Makefile.inc1
  release/amd64/mkisoimages.sh
  release/manifests/freenas-master.json
  release/manifests/trueos-master.json
  release/manifests/trueos-plasma.json
  release/manifests/trueos-snapshot.json
  release/manifests/trueos-stable.json
  release/release-trueos.sh
  release/trueos-manifest.json
Labels: enhancement, review

#177 Add mk-base-jail command to base system, this is used to
  README.md
  release/packages/runtime-development.ucl
  release/release-trueos.sh
  usr.bin/Makefile
  usr.bin/compiler-bootstrap/Makefile
  usr.bin/compiler-bootstrap/Makefile.depend
  usr.bin/compiler-bootstrap/compiler-bootstrap.sh
  usr.bin/mk-base-jail/Makefile
  usr.bin/mk-base-jail/Makefile.depend
  usr.bin/mk-base-jail/mk-base-jail.sh
Labels: enhancement

#183 Add ports.local_source to JSON, which allows different directories to…
  Makefile.inc1
  release/README.md
  release/manifests/freenas-master.json
  release/release-trueos.sh
  release/trueos-manifest.json
Labels: enhancement

#186 Strip plist
  Makefile.inc1
  release/packages/transform-plist.sh
  release/release-trueos.sh
  release/trueos-manifest.json
Labels: enhancement

#189 Add manifest for Gnome
  release/manifests/trueos-gnome.json
Labels: enhancement
